[Project]
name = Plot
description = -

[Plot Data]
attribute source                 = "examples/shaders/plot_data.glsl"
uniform sampler2D previous_frame = last_output_of_ex("Plot Data", GL_NEAREST, GL_CLAMP_TO_EDGE)
uniform ivec2 iresolution        = resolution()
uniform float plot_value_prev    = copy_float("Plot Data", "plot_value")
uniform float thickness          = slider_float("thickness", 1.0, 20.0, 1.0)
uniform float scale              = 1.0/drag_float("scale", 0.001, 0.001, 1000.0, 1.0)
uniform int speed                = drag_int("speed", 0.01, 0, 20, 1)
uniform float plot_value         = eval_float(text_input("Expression", "sin(time())"))
#uniform float plot_value         = eval_float_quiet(read_udp_socket("6969"))
uniform bool reloaded            = reloaded_this_frame()
uniform vec4 plot_color          = color_picker("Plot Color", rgba(0xCC3333FF))

[Plot Scale]
attribute source                 = "examples/shaders/plot_scale.glsl"
uniform sampler2D plot_data      = output_of("Plot Data")
uniform ivec2 iresolution        = resolution()
uniform float scale              = copy_float("Plot Data", "scale")
uniform vec4 bg_color            = background_color()
uniform float scale_pos          = mouse_drag_position().x / float(resolution().x)

